Friend Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const AttackStrengthText = "Attack Strength"
    Friend Const BuyText = "Buy"
    Friend Const CancelText = "Cancel"
    Friend Const ContinueGameText = "Continue Game"
    Friend Const DefendStrengthText = "Defend Strength"
    Friend Const FightText = "Fight!"
    Friend Const FleeText = "Flee"
    Friend Const HitPointText = "Hit Point"
    Friend Const InventoryText = "Inventory"
    Friend Const ItemText = "Item"
    Friend Const LeaveText = "Leave"
    Friend Const LevelUpText = "LEVEL UP!"
    Friend Const MainMenuText = "Main Menu"
    Friend Const NeverMindText = "Never Mind"
    Friend Const StartGameText = "Start Game"
    Friend Const StatusText = "Status"
    Friend Const UseText = "Use"
End Module
